### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by mcdent** [loganmarchione/hassos-addons#8]
Hi Logan, is this still working? 
I've added your repo to an up to date version of HA but for some reason I cannot find your addon when I search for it?
Mike

**Comment by mcdent** [comment]
Thanks, managed to get that sorted ok. However I am unable to correctly authenticate with basic auth.
I've created a file with the hashed password in and am starting Prometheus on the server box with the correct arguments to read that file. I can access the home assistant endpoint with curl using the password just fine.

![Screenshot 2022-08-30 at 15 31 31](https://user-images.githubusercontent.com/8769856/187465074-0376f523-d182-403b-9038-7fa4f12afbf8.jpg)

**Comment by loganmarchione** [comment]
I think the Prometheus config needs to be the plaintext password, not hashed (the bcrypt-hashed password goes into the add-on config). Below is my config.

```
  - job_name: 'homeassistant'
    static_configs:
      - targets: [myserver.mydomain.com:9100']
    basic_auth:
      username: prometheus
      password: asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf
```


When using curl (or visiting the site in your browser), you're not using the hashed password, you're using the plaintext password, right?
